import Head from "next/head";
import Image from "next/image";
import googlePlay from "../public/assets/google-play-svgrepo-com (1).svg";
import appStore from "../public/assets/google-play-svgrepo-com.svg";
import rectangle1 from "../public/assets/Rectangle 68.png";
import rectangle2 from "../public/assets/Rectangle 68 (1).png";
import rectangle3 from "../public/assets/Group 107.png";
import rectangle4 from "../public/assets/Rectangle 54.png";

import fish2 from "../public/assets/pngegg(16) 1.png";
import fish3 from "../public/assets/pngegg(17) 1.png";
import fish4 from "../public/assets/pngegg(12) 1.png";

import phone2 from "../public/assets/1576 1.png";
import phone3 from "../public/assets/15765 1.png";
import comp1 from "../public/assets/Component 1.svg";
import comp2 from "../public/assets/Component 1 (1).svg";
import comp3 from "../public/assets/Component 1 (2).svg";
import group1 from "../public/assets/Group 127.png";
import man from "../public/assets/Mask group.png";
import SliderComp from "../components/Slider";
import Nav from "../components/Nav";
import Hero from "../components/Hero";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className="bg-white flex flex-col">
        {/* Section 1 */}

        <Hero />
        {/* Section 2 */}
        <div className="flex relative h-full">
          <div className="absolute h-full z-20">
            <Image src={rectangle2} alt="Reactangle 2" />
          </div>
          <div className="flex flex-col md:flex-row w-full h-full divide-y md:divide-y-0 md:divide-x bg-red-600">
            <div className="flex flex-col items-center z-30 w-full h-[14rem] lg:h-[18.2rem] justify-between md:w-1/2 py-4 lg:py-10 px-4 md:px-8 lg:px-14">
              <p className="font-medium text-white text-lg md:text-xl lg:text-3xl">
                Lacak Pengiriman anda
              </p>
              <p className="text-white text-sm md:text-base text-justify tracking-tighter lg:tracking-normal">
                A Lorem Ipsum is simply dummy text of the printing and
                typesetting industry. Lorem Ipsum has been the industry's
              </p>
              <div className="flex justify-between w-full gap-4 md:gap-6 lg:gap-8">
                <input
                  type="text"
                  className="bg-white py-2 px-4 rounded-lg lg:rounded-xl w-2/3 shadow focus:outline-none"
                  placeholder="Lacak Pengiriman"
                />
                <button
                  type="button"
                  className="bg-orange-600 text-white p-4 w-1/3 rounded-lg lg:rounded-xl shadow"
                >
                  Lacak
                </button>
              </div>
            </div>
            <div className="flex flex-col items-center z-30 w-full h-[14rem] lg:h-[18.2rem] md:w-1/2 justify-between content-between py-4 lg:py-10 px-4 md:px-8 lg:px-14">
              <p className="font-medium text-white text-lg md:text-xl lg:text-3xl">
                Cek Tarif Pengirman Anda
              </p>
              <div className="flex gap-4 md:gap-6 lg:gap-8 w-full">
                <input
                  type="text"
                  className="bg-white py-4 px-4 rounded-lg lg:rounded-xl w-1/2 shadow focus:outline-none"
                  placeholder="Origin"
                />
                <input
                  type="text"
                  className="bg-white py-4 px-4 rounded-lg lg:rounded-xl w-1/2 shadow focus:outline-none"
                  placeholder="Destination"
                />
              </div>
              <button
                type="button"
                className="bg-orange-600 text-white w-full p-4 rounded-lg lg:rounded-xl shadow"
              >
                Check
              </button>
            </div>
          </div>
        </div>

        {/* Section 3 */}
        <div className="flex flex-col max-w-5xl mx-auto px-4 md:px-8 lg:px-16 xl:px-0 py-8 md:py-14 lg:py-20 gap-4 md:gap-8 lg:gap-12">
          <div className="flex flex-col items-center w-full md:w-1/2 gap-4 lg:gap-6 mx-auto">
            <p className="font-semibold text-xl md:text-3xl lg:text-4xl text-center">
              Keunggulan kami
            </p>
            <p className="text-center text-gray-500">
              A Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-6 lg:gap-8">
            <div className="flex flex-col rounded-xl lg:rounded-3xl border px-4 py-6 md:py-8 lg:py-10 md:px-6 lg:px-8 items-center gap-4">
              <Image src={comp1} alt="Component 1" />
              <p className="font-semibold text-base md:text-lg text-center">
                Kirim Ke Berbagai Negara
              </p>
              <p className="text-gray-500 text-center">
                A Lorem Ipsum is simply dummy text of the printing and
                typesetting industry
              </p>
            </div>
            <div className="flex flex-col rounded-xl lg:rounded-3xl border px-4 py-6 md:py-8 lg:py-10 md:px-6 lg:px-8 items-center gap-4">
              <Image src={comp2} alt="Component 2" />
              <p className="font-semibold text-base md:text-lg text-center">
                Mudah Di Gunakan
              </p>
              <p className="text-gray-500 text-center">
                A Lorem Ipsum is simply dummy text of the printing and
                typesetting industry
              </p>
            </div>
            <div className="flex flex-col rounded-xl lg:rounded-3xl border px-4 py-6 md:py-8 lg:py-10 md:px-6 lg:px-8 items-center gap-4">
              <Image src={comp3} alt="Component 3" />
              <p className="font-semibold text-base md:text-lg text-center">
                Pengiriman Aman
              </p>
              <p className="text-gray-500 text-center">
                A Lorem Ipsum is simply dummy text of the printing and
                typesetting industry
              </p>
            </div>
          </div>
        </div>

        {/* Section 4 */}
        <div className="flex flex-col md:flex-row relative py-4 md:py-10 lg:py-14 h-full">
          <div className="flex flex-col items-center h-48 lg:h-72 py-0 lg:py-8 w-full lg:px-0 md:w-1/2 px-4 md:pl-8 lg:pl-[4.5rem] xl:pl-[7.5rem] gap-4">
            <p className="font-semibold text-lg sm:text-xl md:text-3xl lg:text-4xl">
              Berbagai Metode Pengiriman
            </p>
            <p className="text-gray-500">
              A Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard.
            </p>
          </div>
          <div className="right-0 absolute hidden md:flex justify-center items-center">
            <div className="w-[20rem] lg:w-[26rem] xl:w-[30rem]">
              <Image src={rectangle1} alt="Rectangle 3" />
            </div>
            <div className="absolute z-30 w-32 md:w-40 lg:w-48 xl:w-56 right-60 lg:right-[20rem] xl:right-[23rem]">
              <Image src={fish2} alt="Fish 2" />
            </div>
            <div className="absolute z-30 w-32 md:w-40 lg:w-48 xl:w-56 lg:-top-16 xl:-top-20">
              <Image src={phone2} alt="Phone 2" />
            </div>
          </div>
        </div>

        {/* Section 5 */}
        <div className="flex flex-col md:flex-row relative justify-end py-0 md:py-16 lg:py-16 xl:py-28 h-full">
          <div className="left-0 absolute hidden md:flex py-10">
            <div className="w-[20rem] lg:w-[26rem] xl:w-[29.5rem]">
              <Image src={rectangle3} alt="Rectangle 3" />
            </div>
            <div className="absolute z-30 w-32 md:w-40 lg:w-48 xl:w-56 left-60 lg:left-[19.5rem] xl:left-[22rem] top-14 lg:top-16 xl:top-16">
              <Image src={fish3} alt="Fish 2" />
            </div>
            <div className="w-[21rem] lg:w-[26rem] xl:w-[31rem] absolute -top-[2rem] lg:-top-12 xl:-top-[4.5rem]">
              <Image src={phone3} alt="Rectangle 3" />
            </div>
          </div>
          <div className="flex flex-col items-center pr-4 md:pr-8 lg:pr-20 xl:pr-28 lg:items-start h-48 lg:h-72 py-0 lg:py-8 w-full px-4 lg:px-0 md:w-1/2 gap-4">
            <p className="font-semibold text-lg sm:text-xl md:text-3xl lg:text-4xl">
              Lacak Status Pengiriman Anda
            </p>
            <p className="text-gray-500">
              A Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown. A Lorem Ipsum is simply
              dummy text of the printing and typesetting industry.
            </p>
          </div>
        </div>

        {/* Section 6 */}
        <div className="flex flex-col md:flex-row relative py-16 md:py-20 lg:py-20 xl:py-28 h-full">
          <div className="flex flex-col items-center w-full lg:items-start h-48 lg:h-72 px-4 py-4 md:py-8 lg:px-6 xl:pr-20 md:w-1/2 md:pl-8 lg:pl-[4.5rem] xl:pl-[7.5rem] gap-4">
            <p className="font-semibold text-lg sm:text-xl md:text-3xl lg:text-4xl">
              Cek Schedule Pengiriman Anda
            </p>
            <p className="text-gray-500">
              A Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard.
            </p>
          </div>
          <div className="right-0 absolute hidden md:flex justify-center items-center top-8 lg:top-0">
            <div className="w-[20rem] lg:w-[28rem] xl:w-[34rem]">
              <Image src={group1} alt="Rectangle 3" />
            </div>
            <div className="absolute z-30 w-32 md:w-40 lg:w-48 xl:w-56 right-56 lg:right-[20rem] xl:right-[24rem]">
              <Image src={fish4} alt="Fish 2" />
            </div>
          </div>
        </div>

        {/* Section 7 */}
        <div className="flex flex-col py-4 md:py-10 lg:py-14 xl:py-20 gap-4 lg:gap-10 xl:gap-20">
          <div className="flex flex-col w-full md:w-1/2 mx-auto items-center gap-4 px-4 lg:px-0">
            <p className="text-lg md:text-2xl lg:text-3xl xl:text-4xl font-semibold">
              Testimonial
            </p>
            <p className="text-gray-500 text-center">
              A Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text{" "}
            </p>
          </div>
          <div className="flex flex-col px-4 lg:px-0">
            <SliderComp />
          </div>
        </div>

        {/* Section 8 */}
        <div className="py-4 md:py-10 relative w-full justify-center items-center flex">
          <div className="flex flex-col md:flex-row absolute z-30 max-w-5xl mx-auto w-full bg-red-600 md:bg-transparent">
            <div className="flex flex-col w-full md:w-1/2 gap-2 md:gap-6 lg:gap-8 px-6 md:px-10 py-4 md:py-0">
              <p className="font-semibold text-white text-xl md:text-2xl lg:text-3xl xl:text-4xl">
                Available and Download Anytime!
              </p>
              <p className="text-white">
                A Lorem Ipsum is simply dummy text of the printing and
              </p>
              <div className="flex gap-6">
                <Image src={googlePlay} alt="Google Playstore logo" />
                <Image src={appStore} alt="Google Playstore logo" />
              </div>
            </div>
            <div className="hidden md:flex w-0 md:w-1/2 relative items-start justify-start -top-[5.4rem] lg:-top-32 xl:-top-[11.7rem] px-10">
              <div className="absolute w-72 lg:w-96 xl:w-[30.1rem]">
                <Image src={man} alt="Google Playstore logo" />
              </div>
            </div>
          </div>
          <Image src={rectangle4} alt="" />
        </div>

        {/* Footer */}
        <Footer />
      </main>
    </div>
  );
}
